[package]
name = "jp-holidays-lib"
description = "Japanese holiday library for working with public holiday data in Rust."
version = "1.0.1"
edition = "2024"
authors = ["Chomolungma Shirayuki"]
repository = "https://github.com/46ki75/jp-holidays"
license = "MIT"
documentation = "https://docs.rs/jp-holidays-lib"
categories = ["date-and-time", "internationalization", "data-structures"]
keywords = ["japan", "holiday", "calendar", "datetime", "localization"]
readme = "README.md"

[features]
default = ["time"]
time = ["dep:time"]
chrono = ["dep:chrono"]

[dependencies]
time = { version = "0.3.41", features = ["parsing", "macros"], optional = true }
chrono = { version = "0.4.41", optional = true }
async-trait = "0.1.88"
bytes = "1.10.1"
cfg-if = "1.0.0"
encoding_rs = "0.8.35"
reqwest = { version = "0.12.15", features = [
    "rustls-tls",
], default-features = false }
thiserror = "2.0.12"

[dev-dependencies]
tokio = { version = "1.44.2", features = ["full"] }

[[example]]
name = "basic"
path = "examples/basic.rs"
required-features = ["time"]

[[example]]
name = "cache"
path = "examples/cache.rs"
required-features = ["time"]

[[example]]
name = "get_holiday"
path = "examples/get_holiday.rs"
required-features = ["time"]

[[example]]
name = "is_day_off"
path = "examples/is_day_off.rs"
required-features = ["time"]

[[example]]
name = "is_holiday"
path = "examples/is_holiday.rs"
required-features = ["time"]

[[example]]
name = "list_holidays"
path = "examples/list_holidays.rs"
required-features = ["time"]
